2021-02-10 10:30:30,330:__main__:INFO:Main Login Successful
2021-02-10 10:30:30,333:__main__:INFO:Calculating everything before executing orders..
2021-02-10 10:30:30,334:__main__:INFO:Calculating weekly and monthly expiry dates..
2021-02-10 10:30:30,335:__main__:INFO:weekly expiry is : 11Feb2021, monthly expiry is: 25Feb2021
2021-02-10 10:30:31,545:__main__:INFO:StrikePrice computed as : 15050
2021-02-10 10:30:31,545:__main__:INFO:Input of get_eID fn : NIFTY, ce,11Feb2021,15050
2021-02-10 10:30:31,546:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-10 10:30:32,796:__main__:INFO:Exchange Instrument ID : 46292, {'oty': ['CE'], 'ss': ['46292']}
2021-02-10 10:30:32,802:__main__:INFO:Input of get_eID fn : NIFTY, pe,11Feb2021,15050
2021-02-10 10:30:32,804:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-10 10:30:34,110:__main__:INFO:Exchange Instrument ID : 45191, {'oty': ['CE', 'PE'], 'ss': ['46292', '45191']}
2021-02-10 10:30:34,111:__main__:INFO:Checking margin from user..
2021-02-10 10:30:34,112:__main__:INFO:Checking balance..
2021-02-10 10:30:36,802:__main__:INFO:Balance retreived success, available cash : 1000000000
2021-02-10 10:30:36,803:__main__:INFO: 
              net_cash - 1000000000,
              strikePrice - 15050,
              Nifty Spot - 15041.85,
              BankNifty Spot - None
              exchangeInstrumentID - [46292, 45191]
              
2021-02-10 10:30:36,804:__main__:INFO:All set from prepareVars func.. Giving a go for orders..
2021-02-10 10:30:36,805:__main__:INFO:required variables set-- ready to trigger orders at desired time
2021-02-10 10:30:36,806:__main__:INFO:Required Margin Available.. Taking positions...
2021-02-10 10:30:41,606:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,611:__mp_main__:INFO:Placing Orders.. 

2021-02-10 10:30:41,648:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,665:__mp_main__:INFO:Placing Orders.. 

2021-02-10 10:30:41,667:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,668:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,673:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,686:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,703:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:41,703:__mp_main__:INFO:Main Login Successful
2021-02-10 10:30:42,929:__mp_main__:INFO:Order not placed for - 46292 
2021-02-10 10:30:42,936:__main__:ERROR:got exception - Something wrong with placing order:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Python\First_Choice_Git\xts\strategy\Strategy_2.py", line 420, in placeOrder
    raise Exception('Order not placed')
Exception: Order not placed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\lmahendran\Anaconda3\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\Python\First_Choice_Git\xts\strategy\Strategy_2.py", line 421, in placeOrder
    except Exception():
TypeError: catching classes that do not inherit from BaseException is not allowed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\First_Choice_Git\xts\strategy\Strategy_2.py", line 440, in runOrders
    new_dictR.append(f.result())
  File "D:\Users\lmahendran\Anaconda3\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "D:\Users\lmahendran\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
TypeError: catching classes that do not inherit from BaseException is not allowed
2021-02-10 10:30:42,956:__mp_main__:INFO: 
 Order ID for SELL 45191 is: 10026010 

2021-02-10 10:30:42,956:__mp_main__:INFO:Retreiving OrderBook..
2021-02-10 10:30:45,235:__mp_main__:INFO:OrderBook result retreived success
2021-02-10 10:30:45,235:__mp_main__:INFO:traded price is: 76.8
2021-02-10 10:30:45,442:__main__:INFO:No Orders Placed
2021-02-10 10:30:45,443:__main__:INFO:Not started any multi funcs threaded timer
