2021-02-08 10:46:31,234:__main__:INFO:Main Login Successful
2021-02-08 10:46:31,234:__main__:INFO:Calculating everything before executing orders..
2021-02-08 10:46:31,234:__main__:INFO:Calculating weekly and monthly expiry dates..
2021-02-08 10:46:31,234:__main__:INFO:weekly expiry is : 11Feb2021, monthly expiry is: 25Feb2021
2021-02-08 10:46:32,440:__main__:INFO:StrikePrice computed as : 15100
2021-02-08 10:46:32,456:__main__:INFO:Input of get_eID fn : NIFTY, ce,11Feb2021,15100
2021-02-08 10:46:32,456:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-08 10:46:33,645:__main__:INFO:Exchange Instrument ID : 46308, {'oty': ['CE'], 'ss': ['46308']}
2021-02-08 10:46:33,647:__main__:INFO:Input of get_eID fn : NIFTY, pe,11Feb2021,15100
2021-02-08 10:46:33,649:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-08 10:46:34,802:__main__:INFO:Exchange Instrument ID : 42813, {'oty': ['CE', 'PE'], 'ss': ['46308', '42813']}
2021-02-08 10:46:34,803:__main__:INFO:Checking margin from user..
2021-02-08 10:46:34,803:__main__:INFO:Checking balance..
2021-02-08 10:46:36,000:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:37,120:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:38,249:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:39,423:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:40,543:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:41,749:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:42,948:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:44,107:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:45,282:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:46,434:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:47,583:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:48,716:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:49,869:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:51,024:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:52,222:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:53,396:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:54,461:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:55,611:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:56,759:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:57,895:__main__:ERROR:Your session has been expired 
2021-02-08 10:46:59,029:__main__:ERROR:Your session has been expired 
2021-02-08 10:47:00,241:__main__:ERROR:Your session has been expired 
2021-02-08 10:47:01,417:__main__:ERROR:Your session has been expired 
2021-02-08 10:47:02,573:__main__:ERROR:Your session has been expired 
2021-02-08 10:47:02,851:__main__:ERROR:Unable to reterive info like margin,strikePrice,nfty_ltp,bnknfty_ltp to place order
Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\Strategy_2.py", line 351, in prepareVars
    net_cash = checkBalance()
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\Strategy_2.py", line 306, in checkBalance
    bal_resp = xt.get_balance()
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 275, in get_balance
    response = self._get('user.balance', params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 635, in _get
    return self._request(route, "GET", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 663, in _request
    r = self.reqsession.request(method,
  File "C:\Users\mling\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mling\anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mling\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mling\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\mling\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\mling\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mling\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\mling\anaconda3\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\mling\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\mling\anaconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt
2021-02-08 10:47:02,857:__main__:INFO:Vars not set properly...
